package com.sample
 
import com.sample.Car;

//Insurance price for cars under 40 kw
rule "Rule01"
    when
    c: Car(motorPower<=40 && insurancePrice==0)
    then
    System.out.println("Setting Insurance Price to 10000");
    c.setInsurancePrice(10000);
    update(c);
end

//Insurance price for cars between 40 and 50
rule "Rule02"
    when
    c: Car(motorPower>40 && motorPower<=50 && insurancePrice==0)
    then
    System.out.println("Setting Insurance Price to 11000");
    c.setInsurancePrice(11000);
    update(c);
end

//Insurance price for cars between 50 and 75 kw
rule "Rule03"
    when
    c: Car(motorPower>50 && motorPower<=75 && insurancePrice==0)
    then
    System.out.println("Setting Insurance Price to 15000");
    c.setInsurancePrice(15000);
    update(c);
end

//Insurance price for cars over 75kw
rule "Rule04"
    when
    c: Car(motorPower>75 && insurancePrice==0)
    then
    System.out.println("Setting Insurance Price to 25000");
    c.setInsurancePrice(25000);
    update(c);
end

//First registration
rule "Rule05"
    when
    c: Car(oldPremiumGrade==0 && newPremiumGrade==0)
    then
    System.out.println("Setting New Premium Grade to 4");
    c.setNewPremiumGrade(4);
    update(c);
end

//Lowering new premium grade
rule "Rule06"
    when
    c: Car(oldPremiumGrade!=0 && newPremiumGradeSet==false && accidents==0)
    then
    System.out.println("Lowering New Premium Grade");
	c.setNewPremiumGradeSet(true);
    c.setNewPremiumGrade(c.getOldPremiumGrade()-1);
    update(c);
end

//Raising new premium grade
rule "Rule07"
    when
    c: Car(oldPremiumGrade!=0 && newPremiumGradeSet==false && accidents!=0)
    then
    System.out.println("Raising New Premium Grade");
    c.setNewPremiumGradeSet(true);
    c.setNewPremiumGrade(c.getOldPremiumGrade() + c.getAccidents()*3);
    update(c);
end

//Post-fixing New Premium Grade #1
rule "Rule08"
    when
    c: Car(newPremiumGrade==0 && newPremiumGradeSet==true)
    then
    System.out.println("Fixing New Premium Grade");
    c.setNewPremiumGrade(1);
    update(c);
end

//Post-fixing New Premium Grade #2
rule "Rule09"
    when
    c: Car(newPremiumGrade>12 && newPremiumGradeSet==true)
    then
    System.out.println("Fixing New Premium Grade");
    c.setNewPremiumGrade(12);
    update(c);
end
 
//Calculating final price #1
rule "Rule10"
    when
    c: Car(finalPrice==0 && newPremiumGrade<=4)
    then
    System.out.println("Calculating Final Price");
    c.setFinalPrice(c.getInsurancePrice()*
    	(0.8+c.getNewPremiumGrade()*0.05));
    update(c);
end

//Calculating final price #2
rule "Rule11"
    when
    c: Car(finalPrice==0 && newPremiumGrade>=5)
    then
    System.out.println("Calculating Final Price");
    c.setFinalPrice(c.getInsurancePrice()*
    	(0.2*c.getNewPremiumGrade()+0.1));
    update(c);
end


















	



