package com.sample
 
import com.sample.AirConditioner;

//Setting the power to 9k for appropriate flats
rule "Rule01"
    when
	a : AirConditioner(squareMeters<=50 && multipleRooms==false && acPower==0);
    then
    System.out.println("Setting the power to 9000");
	a.setAcPower(9000);
	update(a)
end

//Setting the power to 12k for appropriate flats
rule "Rule02"
    when
	a : AirConditioner(squareMeters<=50 && multipleRooms==true && acPower==0);
    then
    System.out.println("Setting the power to 12000");
	a.setAcPower(12000);
	update(a)
end

//Setting the power to 12k for appropriate flats
rule "Rule03"
    when
	a : AirConditioner(squareMeters>50 && squareMeters<75 && multipleRooms==false && acPower==0);
    then
    System.out.println("Setting the power to 12000");
	a.setAcPower(12000);
	update(a)
end

//Setting the power to 18k for appropriate flats
rule "Rule04"
    when
	a : AirConditioner(squareMeters>50 && squareMeters<75 && multipleRooms==true && acPower==0);
    then
    System.out.println("Setting the power to 18000");
	a.setAcPower(18000);
	update(a)
end

//Setting the power to 18k for appropriate flats
rule "Rule05"
    when
	a : AirConditioner(squareMeters>=75 && acPower==0);
    then
    System.out.println("Setting the power to 18000");
	a.setAcPower(18000);
	update(a)
end

//Setting the AC type to Movable
rule "Rule06"
    when
	a : AirConditioner(multipleRooms==true && mountable==false && acType=="Mounted");
    then
    System.out.println("Setting AC Type to Movable");
	a.setAcType("Movable");
	update(a)
end

//Setting the AC type to Window-Mounted
rule "Rule07"
    when
	a : AirConditioner(multipleRooms==false && mountable==false && acType=="Mounted");
    then
    System.out.println("Setting AC Type to Window-Mounted");
	a.setAcType("Window-Mounted");
	update(a)
end

//Installing the inverter
rule "Rule08"
    when
	a : AirConditioner(hasInverter==false && (heatingAmount=="Equally" || heatingAmount=="Mostly"));
    then
    System.out.println("Installing the inverter");
	a.setHasInverter(true);
	update(a)
end

//Installing the inverter
rule "Rule09"
    when
	a : AirConditioner(hasInverter==false && heatingWhenItsColdAsFuck==true);
    then
    System.out.println("Installing the inverter");
	a.setHasInverter(true);
	update(a)
end










