package com.sample
 
import com.sample.AirConditioner;
 
rule "Rule04"
    when
       k: AirConditioner(squaredMeters<=50 && heatingMultipleRooms==false &&
       airConditionPower==0)
    then
		k.setAirConditionPower(9000);
		update(k)
end

rule "Rule05"
    when
       k: AirConditioner(squaredMeters<=50 && heatingMultipleRooms==true &&
       airConditionPower==0)
    then
		k.setAirConditionPower(12000);
		update(k);
end

rule "Rule06"
    when
       k: AirConditioner(squaredMeters>50 && squaredMeters<75 && 
       heatingMultipleRooms==false &&
       airConditionPower==0)
    then
		k.setAirConditionPower(12000);
		update(k);
end

rule "Rule07"
    when
       k: AirConditioner(squaredMeters>50 && squaredMeters<75 && 
       heatingMultipleRooms==true &&
       airConditionPower==0)
    then
		k.setAirConditionPower(18000);
		update(k);
end

rule "Rule08"
    when
       k: AirConditioner(squaredMeters>=75 && 
       airConditionPower==0)
    then
		k.setAirConditionPower(18000);
		update(k);
end

rule "Rule09"
    when
       k: AirConditioner(heatingMultipleRooms==true && 
       wallMountingEnabled==false && airConditionType==null)
    then
		k.setAirConditionType("Pokretni");
		update(k);
end

rule "Rule10"
    when
       k: AirConditioner(heatingMultipleRooms==false && 
       wallMountingEnabled==false && airConditionType==null)
    then
		k.setAirConditionType("Prozorni");
		update(k);
end

rule "Bonus"
    when
       k: AirConditioner(wallMountingEnabled==true && airConditionType==null)
    then
		k.setAirConditionType("Obicni");
		update(k);
end

rule "Rule11-1"
    when
       k: AirConditioner((heatingUse=="Podjednako" || 
       heatingUse=="Pretezno") && inverter==false)
    then
		k.setInverter(true);
		update(k);
end

rule "Rule11-2"
    when
       k: AirConditioner(heatingUse=="Retko" && inverter==false)
    then
		k.setInverter(false);
		update(k);
end

rule "Rule12"
    when
       k: AirConditioner(heatingBelowMinus5==true && inverter==false)
    then
		k.setInverter(true);
		update(k);
end












