package com.sample
 
import com.sample.Car;
 
rule "Rule01"
    when
    c : Car((hasLicense==false || age<19 || yearsWithLicense<1) && canRent==true)    
    then
    System.out.println("Setting CanRent to false");
    c.setCanRent(false);
    update(c);
end

rule "Rule02"
    when
    c : Car(canRent==true && yearsWithLicense<5 && mustLeaveDeposit==false)
    then
    System.out.println("Setting MustLeaveDeposit to true");
    c.setMustLeaveDeposit(true);
    update(c);
end

rule "Rule03"
    when
    c : Car(mustLeaveDeposit==true && yearsWithLicense<=3
    && deposit==0)
    then
    System.out.println("Setting Deposit to 50");
    c.setDeposit(50);
    update(c);
end

rule "Rule05"
    when
    c : Car(mustLeaveDeposit==true && yearsWithLicense>3
  	&& yearsWithLicense<5
    && deposit==0)
    then
    System.out.println("Setting Deposit to 30");    
    c.setDeposit(30);
    update(c);
end

rule "Rule06"
    when
    c : Car(canRent==true && yearsWithLicense<=2
  	&& vehicleClass==null)
    then
    System.out.println("Setting Vehicle Class to A,B");  
    c.setVehicleClass("A B");
    update(c);
end

rule "Rule07"
    when
    c : Car(canRent==true && yearsWithLicense>2
    && yearsWithLicense<5
  	&& vehicleClass==null)
    then
    System.out.println("Setting Vehicle Class to A,B,C,D");
    c.setVehicleClass("A B C D");
    update(c);
end

rule "Rule08"
    when
    c : Car(canRent==true && yearsWithLicense>=5 && vehicleClass==null)
    then
    System.out.println("Setting Vehicle Class to A,B,C,D,E,F");
    c.setVehicleClass("A B C D E F");
    update(c);
end


