package com.sample
 
import com.sample.Car;
 
rule "Rule01"
no-loop
    when
    c : Car(hasLicense==false || age<19 || yearsWithLicense<1)
    then
    c.setCanRent(false);
    update(c);
end

rule "Rule02"
no-loop
    when
    c : Car(hasLicense==true && age>=19 && yearsWithLicense>=1)
    then
    c.setCanRent(true);
    update(c);
end


rule "Rule03"
    when
    c : Car(canRent==true && yearsWithLicense<5 && mustLeaveDeposit==null)
    then
    c.setMustLeaveDeposit("yes");
    update(c);
end

rule "Rule03-2"
    when
    c : Car(canRent==true && yearsWithLicense>=5 && mustLeaveDeposit==null)
    then
    c.setMustLeaveDeposit("no");
    update(c);
end

rule "Rule04"
    when
    c : Car(mustLeaveDeposit=="yes" && yearsWithLicense<=3
    && deposit==0)
    then
    c.setDeposit(50);
    update(c);
end

rule "Rule05"
    when
    c : Car(mustLeaveDeposit=="yes" && yearsWithLicense>3
  	&& yearsWithLicense<5
    && deposit==0)
    then
    c.setDeposit(30);
    update(c);
end

rule "Rule06"
    when
    c : Car(canRent==true && yearsWithLicense<=2
  	&& vehicleClass=="")
    then
    c.setVehicleClass("A B");
    update(c);
end

rule "Rule07"
    when
    c : Car(canRent==true && yearsWithLicense>2
    && yearsWithLicense<5
  	&& vehicleClass=="")
    then
    c.setVehicleClass("A B C D");
    update(c);
end

rule "Rule08"
no-loop
    when
    c : Car(canRent==true && yearsWithLicense>=5 && vehicleClass=="")
    then
    c.setVehicleClass("A B C D E F");
    update(c);
end


